--EFETUANDO CARGA DA TABELA DE CATEGORIAS
INSERT INTO TBL_CATEGORIA VALUES (SEQ_CATEGORIA.NEXTVAL, 'ALIMENTAÇÃO');
INSERT INTO TBL_CATEGORIA VALUES (SEQ_CATEGORIA.NEXTVAL, 'TRANSPORTE');
INSERT INTO TBL_CATEGORIA VALUES (SEQ_CATEGORIA.NEXTVAL, 'SAÚDE');
INSERT INTO TBL_CATEGORIA VALUES (SEQ_CATEGORIA.NEXTVAL, 'LAZER');